# Generated by Django 4.2.11 on 2024-03-23 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
